name: Experiment
on: 
  schedule:
  - cron: '0/5 * * * *'
  workflow_dispatch:

jobs:
  job1:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Emit warning
      run: echo "::warning ::Test Warning"
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: echo "$GITHUB_CONTEXT"
