name: Experiment
on: 
  schedule:
  - cron: '*/5 * * * *'
  workflow-dispatch:

jobs:
  job1:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Emit warning
      run: echo "::warning ::Test Warning"
